wandb_version: 1

dataset:
  desc: null
  value: Worms
nb_classes:
  desc: null
  value: 5
epochs:
  desc: null
  value: 100
batch_size:
  desc: null
  value: 64
lr:
  desc: null
  value: 0.001
weight_decay:
  desc: null
  value: 0.0001
_wandb:
  desc: null
  value:
    python_version: 3.12.3
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1714486008.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      4: 3.12.3
      5: 0.16.6
      8:
      - 3
      - 5
      13: windows-amd64
